### ISSUE TITLE
what do you build it with?

### ISSUE THREAD

**Issue by dxcvvxd** [topnotchfreaks/kernel_msm-5.15#1]
sorry, might be a very stupid question, but what do you use to build it (i tried a lot of tcs on a similar kernel and none worked, can you give some links maybe? would heavily appreciate)

**Comment by belowzeroiq** [comment]
im using prebuilt clang from codelinaro manifest

**Comment by belowzeroiq** [comment]
> sorry, might be a very stupid question, but what do you use to build it (i tried a lot of tcs on a similar kernel and none worked, can you give some links maybe? would heavily appreciate)

im using clang from codelinaro manifest
